#!/usr/bin/env python

import os
import pickle

# Migrate PyQt4 QString iconTheme to regular str for compatibility with PyQt5
filepath = os.path.expanduser('~/.nemu/settings')
with open(filepath, 'rb') as f:
    data = pickle.loads(f.read())

if data['iconTheme'] is not None:
    data['iconTheme'] = str(data['iconTheme'])

with open(filepath, 'wb') as f:
    pickle.dump(data, f)
