#!/usr/bin/env python3

import sys
from PyQt5 import QtGui
from PyQt5.QtWidgets import QApplication
from nemupkg.MainForm import *

app = QApplication(sys.argv)

form = MainForm()

sys.exit(app.exec_())
