#!/usr/bin/env python3

import sys
from PyQt6 import QtGui
from PyQt6.QtWidgets import QApplication
from nemupkg.MainForm import *

app = QApplication(sys.argv)

form = MainForm()

sys.exit(app.exec())
